## ----------------------------- Builder stage ----------------------------- ##
FROM python:3.12-slim-bookworm AS builder

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.5.4 /uv /uvx /bin/

# Copy project dependencies
WORKDIR /app
COPY ./pyproject.toml ./pyproject.toml
COPY ./uv.lock ./uv.lock
RUN uv sync --dev --locked

## ---------------------------- Testing stage --------------------------- ##
FROM python:3.12-slim-bookworm AS test

WORKDIR /app

COPY --from=builder /app/.venv .venv
COPY ./src ./src
COPY ./tests ./tests
COPY ./.env.test ./.env.test

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app"

EXPOSE 4001
