services:
  db:
    image: postgres:15
    env_file:
      - .env.test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - test-network
      

  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: yzklalagano/book-digests:test
    env_file:
      - .env.test
    environment:
      ENV: test
    ports:
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
    command: uvicorn src.main:app --host 0.0.0.0 --port 4001 --log-level info


  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: yzklalagano/book-digests:test
    env_file:
      - .env.test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
    command: pytest
    
    
volumes:
  test_data:

networks:
  test-network: