services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dev_data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - dev-network
      

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: yzklalagano/book-digests:dev
    environment:
      ENV: dev
    ports:
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/src
      - ./tests:/tests
    networks:
      - dev-network
    command: >
      sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 4001 --log-level info --reload"


volumes:
  dev_data:

networks:
  dev-network: