## ----------------------------- Builder stage ----------------------------- ##
FROM python:3.12-slim-bookworm AS builder

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.5.4 /uv /uvx /bin/

# Copy project dependencies
WORKDIR /app
COPY ./pyproject.toml ./pyproject.toml
COPY ./uv.lock ./uv.lock
RUN uv sync --dev --locked

## ---------------------------- Development stage --------------------------- ##
FROM python:3.12-slim-bookworm AS dev

WORKDIR /app

COPY --from=builder /app/.venv .venv
COPY ./src ./src
COPY ./tests ./tests
COPY ./migrations ./migrations
COPY ./alembic.ini ./alembic.ini
COPY ./.env.dev ./.env.dev 

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app"

EXPOSE 4001
