services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - test-network
      

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: yzklalagano/book-digests:test
    environment:
      ENV: test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
    command: pytest
    
    
volumes:
  test_data:

networks:
  test-network: