"""Initial database schema.

Revision ID: 89aeb2c5fb9f
Revises: 
Create Date: 2026-03-26 12:14:43.436316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aeb2c5fb9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dim_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('published_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['dim_authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['dim_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fct_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_number', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=5000), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['dim_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fct_digests')
    op.drop_table('dim_chapters')
    op.drop_table('dim_books')
    op.drop_table('dim_authors')
    # ### end Alembic commands ###
