name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env file from GitHub secret
      run: echo "${{ secrets.DOTENV_FILE }}" > .env.test
    
    - name: Build and test the test Docker image
      run: docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit --exit-code-from tests

  push_to_docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the production Docker image
      run: docker build -t yzklalagano/book-digests .

    - name: Login to Docker
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

    - name: Push Image to Docker
      run: docker push yzklalagano/book-digests
